# Generated by Django 4.1 on 2023-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=200),
        ),
    ]
