# Generated by Django 4.1 on 2023-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptic', '0001_initial'),
        ('cryptforces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='question_solved',
            field=models.ManyToManyField(blank=True, to='cryptic.question'),
        ),
    ]
